primeiraChegada=2.5
semente=42
aleatorios=100000

fila1.servidores=2
fila1.capacidade=3
fila1.chegada=1.0,5.0
fila1.atendimento=4.0,5.0

fila2.servidores=1
fila2.capacidade=5
fila2.atendimento=1.0,3.0

roteamento.fila1.fila2=1.0